- name: install nginx server
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Run app pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

# - name: Remove file (delete file)
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: absent

# - name: create html directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: directory

# - name: Download the frontend content 
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#     dest: /tmp/frontend.zip

# - name: download and extract frontend code
#   ansible.builtin.unarchive:
#     src: /tmp/frontend.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes

# restart is needed only  when there is change in configuration of the server. here we are using    handlers to notify when restart is needed otherwise it will not restart the server

- name: Copy expense configuration
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify: 
  - restart nginx

# - name: Restart nginx service
#   ansible.builtin.service:
#     name: nginx
#     state: restarted